# Generated by Django 4.0.5 on 2022-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Betriebsstelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rl_code', models.CharField(max_length=200)),
                ('langname', models.CharField(max_length=200)),
                ('kurzname', models.CharField(max_length=200)),
                ('typ_kurz', models.CharField(max_length=200)),
                ('typ_lang', models.CharField(max_length=200)),
                ('datum_ab', models.CharField(max_length=200)),
                ('niederlassung', models.CharField(max_length=200)),
                ('regionalbereich', models.CharField(max_length=200)),
                ('letzte_aenderung', models.CharField(max_length=200)),
            ],
        ),
    ]
